### PR TITLE
Feature to Master

### PR DESCRIPTION
**Pull request by DickensJuma**
### **Feature to Master**
- Thought about all the elements on the page and how they are grouped together.
- Added Bootstrap to the project 
- Lay out the basic structure of the page using empty semantic HTML elements that are appropriately sized and which are positioned by using the appropriate Bootstrap classes.
- Set up the top title and navigation bar.
- Work way down the page by filling in and positioning the additional sections.
- Try resizing the browser to see if it mimics the behavior of the real Newsweek homepage.
- Push solution to Github.

### CODE REVIEW

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @DickensJuma :wave:
-
Good job with this project! :tada: 
##
1. The page is very responsive. Everything works as it should. 
2. The project's README has been professionally done. Keep it up.
3. The stylesheets are passing all the checks.
- We, however, do have some few changes to carry out before we proceed (see review comment).
##
## [REQUIRED] - Fix - The general width of the page in large screens.
- While I applaud the use of bootstrap classes, one area seems a bit off in its implementation with this project. The width. This is what we have currently 👇 
clone
- A container bootstrap class can help fix this by centring the page properly as it should. that is only one way to do it. You are free to implement it in a way suitable to you, but I would strongly recommend this fix option. We, however, need to achieve this centring; 👇   
newsweek

## [REQUIRED] - EASE OUT - On using styling on the markup.
- Let's remove all the styling in the markup. The markup should only be styled by stylesheets. Remove these and many like these in the markup; 👇 
styles

- [ ] Also, [validate ](https://validator.w3.org/nu/#textarea) your markup to remove the current errors. 
   

Please make these changes and submit another review request.
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by lekegitrepo** [comment]
#### Hi @DickensJuma :clap: 
#### You did a good job by removing the inline style from the Html tags in the page. However, there's a validation error in the Html and the page should occupy the width of the page like the original.

**_fix this and submit for review._**

**_if you have any doubts or questions contact me on slack._**

### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Review by rOluochKe — APPROVED** [review]
Hello @DickensJuma 
### Good job you have done and for also making changes to the previous reviews :clap: Your project looks good and I approve of it. Congratulations :boom: :100:
### You can now merge and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
